version: "3"

services:
  django_app:
    build: .
    restart: unless-stopped
    volumes:
      - static:/code/static
      - .:/code
      
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    init: true
    tty: true
    ports:
      - "90:90"
    volumes:
      - static:/code/static
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ../UNAH-VINCULACION/configuracion/certbot/www:/var/www/certbot/:ro
      - ../UNAH-VINCULACION/configuracion/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - django_app

volumes:
  .:
  static:
