version: "3"

services:
  django_app:
    build: .
    restart: unless-stopped
    volumes:
      - static:/code/static
      - .:/code
      
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    init: true
    tty: true
    ports:
      - "90:90"
    volumes:
      - static:/code/static
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ../UNAH-VINCULACION/configuracion/certbot/www:/var/www/certbot/:ro
      - ../UNAH-VINCULACION/configuracion/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - django_app

    #MySQL
  db:
    container_name: db
    image: mysql:latest
    init: true
    environment:
      - MYSQL_ROOT_PASSWORD=R3m3d10s2021
      - MYSQL_DATABASE=panchobot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

volumes:
  .:
  static:

  dbdata:
    driver: local
